import { Course } from './course.js';

export const dataCourses = [
  new Course(1, "Betty la fea", "RCN",2,"./images/Yo_soy_Betty,_la_Fea.jpg"," Yo soy Betty, la fea es una telenovela colombiana creada por RCN Televisión y escrita por Fernando Gaitán. La serie se estrenó el 25 de octubre de 1999 y finalizó el 8 de mayo de 2001. La trama se centra en Beatriz Aurora Pinzón Solano, una economista joven y brillante pero poco atractiva que trabaja como secretaria de presidencia en una empresa llamada Ecomoda 1. La serie fue incluida en el Libro Guinness de los récords como la «telenovela más exitosa de la historia de la televisión» en 1999. Desde su lanzamiento en plataformas digitales, se mantuvo en Netflix en el top 10 de programas más visto dentro de Latinoamérica. ","https://www.youtube.com/watch?v=xTO-rrvZ9Dc"),
  new Course(2, "Café con Aroma de Mujer","RCN", 1,"./images/cafe_con_aroma_de_mujer.jpg","Café con aroma de mujer es una telenovela colombiana creada por Fernando Gaitán y producida por RCN Televisión para el desaparecido Canal A, en 1994. La serie se centra en Teresa Suárez, apodada “Gaviota”, una recolectora de café que trabaja en la hacienda Casablanca en Filandia, Colombia, junto a su madre. Un día, conoce a Sebastián Vallejo, el nieto del dueño de la hacienda, y se enamoran perdidamente. A pesar de las diferencias sociales y económicas entre ellos, deciden casarse. La serie fue galardonada con el premio TVyNovelas a la Mejor Telenovela en 1995.","https://www.youtube.com/watch?v=4NiHKIM3Xao"),
  new Course(3, "Sin senos si hay paraíso","Fox", 3,"./images/sin_senos_si_hay_paraiso.jpg","Sin senos sí hay paraíso es una telenovela colombiana creada por Gustavo Bolívar y producida por Telemundo Global Studios y Fox Telecolombia. La serie se centra en Catalina Santana, una joven que vive en un pequeño pueblo controlado por la mafia y que busca venganza contra aquellos que destrozaron e injustamente encarcelaron a su familia. La serie fue galardonada con el premio TVyNovelas a la Mejor Telenovela en 2017. ","https://www.youtube.com/watch?v=s3KM0PUk3LE"),
  new Course(4, "Los Briceño","Caracol", 1,"./images/los-briceno.jpg","Los Briceño es una telenovela colombiana de comedia dramática producida por Juan Carlos Villamizar para Caracol Televisión y distribuida por Caracol Internacional y Netflix. La serie se centra en Cecilia Araminta de los Ángeles Briceño Calvache, apodada “La Chiqui”, la hija menor de una familia de camioneros muy arraigada a sus raíces y muy anticuada. Cuando Cecilia se queda embarazada a sus dieciséis años, su familia decide no perdonarla. Debido a que su familia es muy machista, decide no revelar la identidad del padre de su hijo para no empeorar su situación, por lo que su padre no duda en echarla de la casa. La serie cuenta la historia de cómo Cecilia lucha por sobrevivir y triunfar en un mundo dominado por hombres, mientras cría a su hijo y trata de encontrar el amor verdadero.","https://www.youtube.com/watch?v=I3bm5gDnGwo"),
  new Course(5, "La reina del flow", "Caracol", 2,"./images/la_reina_del_flow.jpg","La reina del flow” es una telenovela colombiana producida por Teleset y Sony Pictures Television para Caracol Televisión en 2018 y 2021. La serie se desarrolla en el emocionante ambiente del reggaeton y cuenta la historia de Yeimy Montoya, una humilde y talentosa joven amante de la música urbana que sueña con convertirse en la mejor exponente del medio. Después de ser injustamente condenada a prisión durante diecisiete años, Yeimy llega a un acuerdo para conseguir su libertad y así poder empezar una venganza contra el hombre que amaba. La serie está protagonizada por Carolina Ramírez, Carlos Torres y Andrés Sandoval, junto con Lucho Velasco y Marcelo Dos Santos (en la segunda temporada) en los roles antagónicos.","https://www.youtube.com/watch?v=xRr7oH2PCP0"),
  new Course(6,"Distrito Salvaje","Netflix",2,"./images/distrito_salvaje.jpg","Distrito salvaje” es una serie de televisión colombiana producida por Dynamo para Netflix en 2018 y 2019. La serie cuenta la historia de Jhon Jeiver, un guerrillero que se muda de la selva a Bogotá después de la firma del Tratado de Paz. La serie se centra en la lucha de Jhon por reintegrarse en la sociedad y reconectarse con su familia, mientras se enfrenta a un sistema político corrupto. La serie está protagonizada por Juan Pablo Raba, Cristina Umaña y Camila Sodi.","https://www.youtube.com/watch?v=2dOvYY7_G8A")
] 